site_name: Project Elephant Documentation

theme:
  name: material

  features:
    # - navigation.sections      
    - search.suggest           
    - search.highlight         
    - content.code.copy       
    - content.tooltips         
  
  palette: 
    - scheme: default
      primary: teal            
      accent: blue             
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode

    - scheme: slate
      primary: teal
      accent: blue 
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

markdown_extensions:
  - admonition                 
  - pymdownx.details          
  - pymdownx.superfences       
  - attr_list                 
  - pymdownx.tabbed:           
      alternate_style: true 

nav:
  - Home: index.md
  - Introduction:
    - Project Overview: Introduction/overview.md
    - Jitsi Meet: Introduction/jitsi-meet.md
    - NICE DCV: Introduction/nice-dcv.md
    - Open World Agents: Introduction/open-world-agents.md
    - Windows: Introduction/windows.md
    - Amazon Web Services: Introduction/amazon-web-services.md
  - Phase 1 - Setting up EC2, DCV and OCAP:
    - Overview: Phase 1/index.md
    - EC2: Phase 1/ec2.md
    - DCV: Phase 1/dcv.md
    - OCAP: Phase 1/ocap.md
    - Fork Discussion: Phase 1/fork-discussion.md
  - Phase 2 - OCAP Automation and S3:
    - Overview: Phase 2/index.md
    - S3 Setup: Phase 2/s3-setup.md
    - IAM Roles and AWS Tools: Phase 2/iam-aws-tools.md
    - OCAP Scripts: Phase 2/ocap-scripts.md
    - Task Scheduler: Phase 2/task-scheduler.md