site_name: Project Elephant Documentation
theme:
  name: material
  palette: 
    primary: teal
    accent: purple

# This allows you to organize your pages in the sidebar
nav:
  - Home: index.md
  - Introduction:
    - Project Overview: Introduction/overview.md
    - Jitsi Meet: Introduction/jitsi-meet.md
    - NICE DCV: Introduction/nice-dcv.md
    - Open World Agents: Introduction/open-world-agents.md
    - Windows: Introduction/windows.md
    - Amazon Web Services: Introduction/amazon-web-services.md